---
- Virtual Maschine:
    - Windows Server 2022:
        icon: mdi-microsoft-windows
        href: http://localhost:8006

    - Debian:
        icon: mdi-debian
        href: http://localhost:8007
        
- Visual Studio Code:
    - Programmierung:
        icon: mdi-microsoft-visual-studio-code
        href: http://localhost:8080